"""可观测的工作流事件 Schema。"""

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, JsonValue

from app.schemas.common import Identifier, NonEmptyStr


class WorkflowEventType(StrEnum):
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    NODE_FAILED = "NODE_FAILED"
    MODEL_CALL_STARTED = "MODEL_CALL_STARTED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"
    MODEL_CALL_RETRIED = "MODEL_CALL_RETRIED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    TOOL_CALL_RETRIED = "TOOL_CALL_RETRIED"
    SOURCE_FETCHED = "SOURCE_FETCHED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    EVIDENCE_REJECTED = "EVIDENCE_REJECTED"
    RESEARCH_STOPPED = "RESEARCH_STOPPED"
    RESEARCH_PROGRESS_UPDATED = "RESEARCH_PROGRESS_UPDATED"
    SUPPLEMENT_STARTED = "SUPPLEMENT_STARTED"
    SUPPLEMENT_COMPLETED = "SUPPLEMENT_COMPLETED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_PASSED = "REVIEW_PASSED"
    REVIEW_FAILED = "REVIEW_FAILED"
    REVISION_STARTED = "REVISION_STARTED"
    REVISION_COMPLETED = "REVISION_COMPLETED"
    REPORT_URLS_REDACTED = "REPORT_URLS_REDACTED"
    CITATION_REPAIR_STARTED = "CITATION_REPAIR_STARTED"
    CITATION_REPAIR_COMPLETED = "CITATION_REPAIR_COMPLETED"
    REPORT_VALIDATION_FAILED = "REPORT_VALIDATION_FAILED"
    CONFLICTS_IDENTIFIED = "CONFLICTS_IDENTIFIED"
    # 交付前的确定性自检（零模型调用）：例如引文落在来源的已废弃段落内。
    DELIVERY_SELF_CHECK_COMPLETED = "DELIVERY_SELF_CHECK_COMPLETED"
    WORKFLOW_BUDGET_EXCEEDED = "WORKFLOW_BUDGET_EXCEEDED"


class WorkflowEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    event_id: Identifier
    sequence: int = Field(gt=0)
    task_id: Identifier
    event_type: WorkflowEventType
    stage: NonEmptyStr
    timestamp: AwareDatetime
    payload: dict[str, JsonValue]
